version: "3"

services: 
  easy-orders-backend:
    image: easy-orders-backend:dev-0.1
    build:
      context: .
      dockerfile: test.Dockerfile 
    command: >
      sh -c "
      #python manage.py wait_for_db && 
      #python manage.py migrate &&
             python manage.py test"
    environment: 
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=test123
    depends_on: 
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test123